/** Cities, governorates and provinces per country — used for local price scopes. */

export type City = { id: string; ar: string; en: string };

export const CITIES: Record<string, City[]> = {
  SA: [
    { id: "riyadh", ar: "الرياض", en: "Riyadh" },
    { id: "makkah", ar: "مكة المكرمة", en: "Makkah" },
    { id: "madinah", ar: "المدينة المنورة", en: "Madinah" },
    { id: "qassim", ar: "القصيم", en: "Qassim" },
    { id: "eastern-province", ar: "المنطقة الشرقية", en: "Eastern Province" },
    { id: "asir", ar: "عسير", en: "Asir" },
    { id: "tabuk", ar: "تبوك", en: "Tabuk" },
    { id: "hail", ar: "حائل", en: "Hail" },
    { id: "northern-borders", ar: "الحدود الشمالية", en: "Northern Borders" },
    { id: "jazan", ar: "جازان", en: "Jazan" },
    { id: "najran", ar: "نجران", en: "Najran" },
    { id: "al-bahah", ar: "الباحة", en: "Al Bahah" },
    { id: "al-jouf", ar: "الجوف", en: "Al Jouf" },
  ],
  EG: [
    { id: "cairo", ar: "القاهرة", en: "Cairo" },
    { id: "giza", ar: "الجيزة", en: "Giza" },
    { id: "alexandria", ar: "الإسكندرية", en: "Alexandria" },
    { id: "qalyubia", ar: "القليوبية", en: "Qalyubia" },
    { id: "sharqia", ar: "الشرقية", en: "Sharqia" },
    { id: "dakahlia", ar: "الدقهلية", en: "Dakahlia" },
    { id: "gharbia", ar: "الغربية", en: "Gharbia" },
    { id: "monufia", ar: "المنوفية", en: "Monufia" },
    { id: "beheira", ar: "البحيرة", en: "Beheira" },
    { id: "kafr-el-sheikh", ar: "كفر الشيخ", en: "Kafr El Sheikh" },
    { id: "damietta", ar: "دمياط", en: "Damietta" },
    { id: "port-said", ar: "بورسعيد", en: "Port Said" },
    { id: "ismailia", ar: "الإسماعيلية", en: "Ismailia" },
    { id: "suez", ar: "السويس", en: "Suez" },
    { id: "north-sinai", ar: "شمال سيناء", en: "North Sinai" },
    { id: "south-sinai", ar: "جنوب سيناء", en: "South Sinai" },
    { id: "red-sea", ar: "البحر الأحمر", en: "Red Sea" },
    { id: "matrouh", ar: "مطروح", en: "Matrouh" },
    { id: "fayoum", ar: "الفيوم", en: "Fayoum" },
    { id: "beni-suef", ar: "بني سويف", en: "Beni Suef" },
    { id: "minya", ar: "المنيا", en: "Minya" },
    { id: "asyut", ar: "أسيوط", en: "Asyut" },
    { id: "sohag", ar: "سوهاج", en: "Sohag" },
    { id: "qena", ar: "قنا", en: "Qena" },
    { id: "luxor", ar: "الأقصر", en: "Luxor" },
    { id: "aswan", ar: "أسوان", en: "Aswan" },
    { id: "new-valley", ar: "الوادي الجديد", en: "New Valley" },
  ],
  AE: [
    { id: "abu-dhabi", ar: "أبوظبي", en: "Abu Dhabi" },
    { id: "dubai", ar: "دبي", en: "Dubai" },
    { id: "sharjah", ar: "الشارقة", en: "Sharjah" },
    { id: "ajman", ar: "عجمان", en: "Ajman" },
    { id: "umm-al-quwain", ar: "أم القيوين", en: "Umm Al Quwain" },
    { id: "ras-al-khaimah", ar: "رأس الخيمة", en: "Ras Al Khaimah" },
    { id: "fujairah", ar: "الفجيرة", en: "Fujairah" },
  ],
  KW: [
    { id: "al-asimah", ar: "العاصمة", en: "Al Asimah" },
    { id: "hawalli", ar: "حولي", en: "Hawalli" },
    { id: "farwaniya", ar: "الفروانية", en: "Farwaniya" },
    { id: "mubarak-al-kabeer", ar: "مبارك الكبير", en: "Mubarak Al-Kabeer" },
    { id: "ahmadi", ar: "الأحمدي", en: "Ahmadi" },
    { id: "jahra", ar: "الجهراء", en: "Jahra" },
  ],
  QA: [
    { id: "doha", ar: "الدوحة", en: "Doha" },
    { id: "al-rayyan", ar: "الريان", en: "Al Rayyan" },
    { id: "al-wakrah", ar: "الوكرة", en: "Al Wakrah" },
    { id: "umm-salal", ar: "أم صلال", en: "Umm Salal" },
    { id: "al-khor", ar: "الخور", en: "Al Khor" },
    { id: "al-shamal", ar: "الشمال", en: "Al Shamal" },
    { id: "al-daayen", ar: "الضعاين", en: "Al Daayen" },
    { id: "al-shahaniya", ar: "الشحانية", en: "Al Shahaniya" },
  ],
  BH: [
    { id: "capital", ar: "العاصمة", en: "Capital" },
    { id: "muharraq", ar: "المحرق", en: "Muharraq" },
    { id: "northern", ar: "الشمالية", en: "Northern" },
    { id: "southern", ar: "الجنوبية", en: "Southern" },
  ],
  OM: [
    { id: "muscat", ar: "مسقط", en: "Muscat" },
    { id: "dhofar", ar: "ظفار", en: "Dhofar" },
    { id: "musandam", ar: "مسندم", en: "Musandam" },
    { id: "al-buraimi", ar: "البريمي", en: "Al Buraimi" },
    { id: "ad-dakhiliyah", ar: "الداخلية", en: "Ad Dakhiliyah" },
    { id: "north-al-batinah", ar: "شمال الباطنة", en: "North Al Batinah" },
    { id: "south-al-batinah", ar: "جنوب الباطنة", en: "South Al Batinah" },
    { id: "north-ash-sharqiyah", ar: "شمال الشرقية", en: "North Ash Sharqiyah" },
    { id: "south-ash-sharqiyah", ar: "جنوب الشرقية", en: "South Ash Sharqiyah" },
    { id: "ad-dhahirah", ar: "الظاهرة", en: "Ad Dhahirah" },
    { id: "al-wusta", ar: "الوسطى", en: "Al Wusta" },
  ],
  JO: [
    { id: "amman", ar: "عمّان", en: "Amman" },
    { id: "irbid", ar: "إربد", en: "Irbid" },
    { id: "zarqa", ar: "الزرقاء", en: "Zarqa" },
    { id: "balqa", ar: "البلقاء", en: "Balqa" },
    { id: "madaba", ar: "مأدبا", en: "Madaba" },
    { id: "mafraq", ar: "المفرق", en: "Mafraq" },
    { id: "jerash", ar: "جرش", en: "Jerash" },
    { id: "ajloun", ar: "عجلون", en: "Ajloun" },
    { id: "karak", ar: "الكرك", en: "Karak" },
    { id: "tafilah", ar: "الطفيلة", en: "Tafilah" },
    { id: "ma-an", ar: "معان", en: "Ma'an" },
    { id: "aqaba", ar: "العقبة", en: "Aqaba" },
  ],
  IQ: [
    { id: "baghdad", ar: "بغداد", en: "Baghdad" },
    { id: "basra", ar: "البصرة", en: "Basra" },
    { id: "nineveh", ar: "نينوى", en: "Nineveh" },
    { id: "erbil", ar: "أربيل", en: "Erbil" },
    { id: "sulaymaniyah", ar: "السليمانية", en: "Sulaymaniyah" },
    { id: "duhok", ar: "دهوك", en: "Duhok" },
    { id: "kirkuk", ar: "كركوك", en: "Kirkuk" },
    { id: "diyala", ar: "ديالى", en: "Diyala" },
    { id: "anbar", ar: "الأنبار", en: "Anbar" },
    { id: "saladin", ar: "صلاح الدين", en: "Saladin" },
    { id: "babil", ar: "بابل", en: "Babil" },
    { id: "karbala", ar: "كربلاء", en: "Karbala" },
    { id: "najaf", ar: "النجف", en: "Najaf" },
    { id: "wasit", ar: "واسط", en: "Wasit" },
    { id: "qadisiyyah", ar: "القادسية", en: "Qadisiyyah" },
    { id: "muthanna", ar: "المثنى", en: "Muthanna" },
    { id: "dhi-qar", ar: "ذي قار", en: "Dhi Qar" },
    { id: "maysan", ar: "ميسان", en: "Maysan" },
  ],
  SY: [
    { id: "damascus", ar: "دمشق", en: "Damascus" },
    { id: "rif-dimashq", ar: "ريف دمشق", en: "Rif Dimashq" },
    { id: "aleppo", ar: "حلب", en: "Aleppo" },
    { id: "homs", ar: "حمص", en: "Homs" },
    { id: "hama", ar: "حماة", en: "Hama" },
    { id: "latakia", ar: "اللاذقية", en: "Latakia" },
    { id: "tartus", ar: "طرطوس", en: "Tartus" },
    { id: "idlib", ar: "إدلب", en: "Idlib" },
    { id: "daraa", ar: "درعا", en: "Daraa" },
    { id: "as-suwayda", ar: "السويداء", en: "As-Suwayda" },
    { id: "quneitra", ar: "القنيطرة", en: "Quneitra" },
    { id: "deir-ez-zor", ar: "دير الزور", en: "Deir ez-Zor" },
    { id: "raqqa", ar: "الرقة", en: "Raqqa" },
    { id: "hasakah", ar: "الحسكة", en: "Hasakah" },
  ],
  YE: [
    { id: "sanaa", ar: "صنعاء", en: "Sanaa" },
    { id: "aden", ar: "عدن", en: "Aden" },
    { id: "taiz", ar: "تعز", en: "Taiz" },
    { id: "hodeidah", ar: "الحديدة", en: "Hodeidah" },
    { id: "ibb", ar: "إب", en: "Ibb" },
    { id: "hadhramaut", ar: "حضرموت", en: "Hadhramaut" },
    { id: "dhamar", ar: "ذمار", en: "Dhamar" },
    { id: "hajjah", ar: "حجة", en: "Hajjah" },
    { id: "al-mahwit", ar: "المحويت", en: "Al Mahwit" },
    { id: "saada", ar: "صعدة", en: "Saada" },
    { id: "marib", ar: "مأرب", en: "Marib" },
    { id: "al-jawf", ar: "الجوف", en: "Al Jawf" },
    { id: "al-bayda", ar: "البيضاء", en: "Al Bayda" },
    { id: "lahij", ar: "لحج", en: "Lahij" },
    { id: "abyan", ar: "أبين", en: "Abyan" },
    { id: "shabwah", ar: "شبوة", en: "Shabwah" },
    { id: "al-mahrah", ar: "المهرة", en: "Al Mahrah" },
    { id: "al-dhale", ar: "الضالع", en: "Al Dhale" },
    { id: "raymah", ar: "ريمة", en: "Raymah" },
    { id: "amran", ar: "عمران", en: "Amran" },
    { id: "socotra", ar: "سقطرى", en: "Socotra" },
  ],
  SD: [
    { id: "khartoum", ar: "الخرطوم", en: "Khartoum" },
    { id: "al-jazirah", ar: "الجزيرة", en: "Al Jazirah" },
    { id: "gedaref", ar: "القضارف", en: "Gedaref" },
    { id: "kassala", ar: "كسلا", en: "Kassala" },
    { id: "red-sea", ar: "البحر الأحمر", en: "Red Sea" },
    { id: "river-nile", ar: "نهر النيل", en: "River Nile" },
    { id: "northern", ar: "الشمالية", en: "Northern" },
    { id: "north-kordofan", ar: "شمال كردفان", en: "North Kordofan" },
    { id: "south-kordofan", ar: "جنوب كردفان", en: "South Kordofan" },
    { id: "west-kordofan", ar: "غرب كردفان", en: "West Kordofan" },
    { id: "north-darfur", ar: "شمال دارفور", en: "North Darfur" },
    { id: "south-darfur", ar: "جنوب دارفور", en: "South Darfur" },
    { id: "west-darfur", ar: "غرب دارفور", en: "West Darfur" },
    { id: "east-darfur", ar: "شرق دارفور", en: "East Darfur" },
    { id: "central-darfur", ar: "وسط دارفور", en: "Central Darfur" },
    { id: "sennar", ar: "سنار", en: "Sennar" },
    { id: "white-nile", ar: "النيل الأبيض", en: "White Nile" },
    { id: "blue-nile", ar: "النيل الأزرق", en: "Blue Nile" },
  ],
  LY: [
    { id: "tripoli", ar: "طرابلس", en: "Tripoli" },
    { id: "benghazi", ar: "بنغازي", en: "Benghazi" },
    { id: "misrata", ar: "مصراتة", en: "Misrata" },
    { id: "zawiya", ar: "الزاوية", en: "Zawiya" },
    { id: "sabha", ar: "سبها", en: "Sabha" },
    { id: "bayda", ar: "البيضاء", en: "Bayda" },
    { id: "derna", ar: "درنة", en: "Derna" },
    { id: "tobruk", ar: "طبرق", en: "Tobruk" },
    { id: "sirte", ar: "سرت", en: "Sirte" },
    { id: "khoms", ar: "الخمس", en: "Khoms" },
    { id: "gharyan", ar: "غريان", en: "Gharyan" },
    { id: "ajdabiya", ar: "أجدابيا", en: "Ajdabiya" },
    { id: "zliten", ar: "زليتن", en: "Zliten" },
    { id: "kufra", ar: "الكفرة", en: "Kufra" },
    { id: "ghat", ar: "غات", en: "Ghat" },
    { id: "nalut", ar: "نالوت", en: "Nalut" },
    { id: "jufra", ar: "الجفرة", en: "Jufra" },
    { id: "marj", ar: "المرج", en: "Marj" },
  ],
  TN: [
    { id: "tunis", ar: "تونس", en: "Tunis" },
    { id: "ariana", ar: "أريانة", en: "Ariana" },
    { id: "ben-arous", ar: "بن عروس", en: "Ben Arous" },
    { id: "manouba", ar: "منوبة", en: "Manouba" },
    { id: "nabeul", ar: "نابل", en: "Nabeul" },
    { id: "zaghouan", ar: "زغوان", en: "Zaghouan" },
    { id: "bizerte", ar: "بنزرت", en: "Bizerte" },
    { id: "beja", ar: "باجة", en: "Beja" },
    { id: "jendouba", ar: "جندوبة", en: "Jendouba" },
    { id: "kef", ar: "الكاف", en: "Kef" },
    { id: "siliana", ar: "سليانة", en: "Siliana" },
    { id: "sousse", ar: "سوسة", en: "Sousse" },
    { id: "monastir", ar: "المنستير", en: "Monastir" },
    { id: "mahdia", ar: "المهدية", en: "Mahdia" },
    { id: "sfax", ar: "صفاقس", en: "Sfax" },
    { id: "kairouan", ar: "القيروان", en: "Kairouan" },
    { id: "kasserine", ar: "القصرين", en: "Kasserine" },
    { id: "sidi-bouzid", ar: "سيدي بوزيد", en: "Sidi Bouzid" },
    { id: "gabes", ar: "قابس", en: "Gabes" },
    { id: "medenine", ar: "مدنين", en: "Medenine" },
    { id: "tataouine", ar: "تطاوين", en: "Tataouine" },
    { id: "gafsa", ar: "قفصة", en: "Gafsa" },
    { id: "tozeur", ar: "توزر", en: "Tozeur" },
    { id: "kebili", ar: "قبلي", en: "Kebili" },
  ],
  DZ: [
    { id: "algiers", ar: "الجزائر", en: "Algiers" },
    { id: "oran", ar: "وهران", en: "Oran" },
    { id: "constantine", ar: "قسنطينة", en: "Constantine" },
    { id: "annaba", ar: "عنابة", en: "Annaba" },
    { id: "batna", ar: "باتنة", en: "Batna" },
    { id: "setif", ar: "سطيف", en: "Setif" },
    { id: "sidi-bel-abbes", ar: "سيدي بلعباس", en: "Sidi Bel Abbes" },
    { id: "biskra", ar: "بسكرة", en: "Biskra" },
    { id: "tlemcen", ar: "تلمسان", en: "Tlemcen" },
    { id: "bejaia", ar: "بجاية", en: "Bejaia" },
    { id: "tizi-ouzou", ar: "تيزي وزو", en: "Tizi Ouzou" },
    { id: "blida", ar: "البليدة", en: "Blida" },
    { id: "jijel", ar: "جيجل", en: "Jijel" },
    { id: "ouargla", ar: "ورقلة", en: "Ouargla" },
    { id: "ghardaia", ar: "غرداية", en: "Ghardaia" },
    { id: "adrar", ar: "أدرار", en: "Adrar" },
    { id: "tamanrasset", ar: "تمنراست", en: "Tamanrasset" },
    { id: "m-sila", ar: "المسيلة", en: "M'Sila" },
    { id: "chlef", ar: "الشلف", en: "Chlef" },
    { id: "mostaganem", ar: "مستغانم", en: "Mostaganem" },
    { id: "tiaret", ar: "تيارت", en: "Tiaret" },
    { id: "el-oued", ar: "الوادي", en: "El Oued" },
    { id: "bechar", ar: "بشار", en: "Bechar" },
    { id: "skikda", ar: "سكيكدة", en: "Skikda" },
    { id: "guelma", ar: "قالمة", en: "Guelma" },
  ],
  MA: [
    { id: "casablanca-settat", ar: "الدار البيضاء سطات", en: "Casablanca-Settat" },
    { id: "rabat-sale-kenitra", ar: "الرباط سلا القنيطرة", en: "Rabat-Sale-Kenitra" },
    { id: "fes-meknes", ar: "فاس مكناس", en: "Fes-Meknes" },
    { id: "marrakech-safi", ar: "مراكش آسفي", en: "Marrakech-Safi" },
    { id: "tanger-tetouan-al-hoceima", ar: "طنجة تطوان الحسيمة", en: "Tanger-Tetouan-Al Hoceima" },
    { id: "oriental", ar: "الشرق", en: "Oriental" },
    { id: "beni-mellal-khenifra", ar: "بني ملال خنيفرة", en: "Beni Mellal-Khenifra" },
    { id: "souss-massa", ar: "سوس ماسة", en: "Souss-Massa" },
    { id: "draa-tafilalet", ar: "درعة تافيلالت", en: "Draa-Tafilalet" },
    { id: "guelmim-oued-noun", ar: "كلميم واد نون", en: "Guelmim-Oued Noun" },
    { id: "laayoune-sakia-el-hamra", ar: "العيون الساقية الحمراء", en: "Laayoune-Sakia El Hamra" },
    { id: "dakhla-oued-ed-dahab", ar: "الداخلة وادي الذهب", en: "Dakhla-Oued Ed-Dahab" },
  ],
  PS: [
    { id: "jerusalem", ar: "القدس", en: "Jerusalem" },
    { id: "ramallah", ar: "رام الله والبيرة", en: "Ramallah" },
    { id: "nablus", ar: "نابلس", en: "Nablus" },
    { id: "hebron", ar: "الخليل", en: "Hebron" },
    { id: "bethlehem", ar: "بيت لحم", en: "Bethlehem" },
    { id: "jenin", ar: "جنين", en: "Jenin" },
    { id: "tulkarm", ar: "طولكرم", en: "Tulkarm" },
    { id: "qalqilya", ar: "قلقيلية", en: "Qalqilya" },
    { id: "salfit", ar: "سلفيت", en: "Salfit" },
    { id: "jericho", ar: "أريحا", en: "Jericho" },
    { id: "tubas", ar: "طوباس", en: "Tubas" },
    { id: "gaza", ar: "غزة", en: "Gaza" },
    { id: "north-gaza", ar: "شمال غزة", en: "North Gaza" },
    { id: "deir-al-balah", ar: "دير البلح", en: "Deir al-Balah" },
    { id: "khan-younis", ar: "خان يونس", en: "Khan Younis" },
    { id: "rafah", ar: "رفح", en: "Rafah" },
  ],
  LB: [
    { id: "beirut", ar: "بيروت", en: "Beirut" },
    { id: "mount-lebanon", ar: "جبل لبنان", en: "Mount Lebanon" },
    { id: "north", ar: "الشمال", en: "North" },
    { id: "akkar", ar: "عكار", en: "Akkar" },
    { id: "beqaa", ar: "البقاع", en: "Beqaa" },
    { id: "baalbek-hermel", ar: "بعلبك الهرمل", en: "Baalbek-Hermel" },
    { id: "south", ar: "الجنوب", en: "South" },
    { id: "nabatieh", ar: "النبطية", en: "Nabatieh" },
  ],
  TR: [
    { id: "istanbul", ar: "إسطنبول", en: "Istanbul" },
    { id: "ankara", ar: "أنقرة", en: "Ankara" },
    { id: "izmir", ar: "إزمير", en: "Izmir" },
    { id: "bursa", ar: "بورصة", en: "Bursa" },
    { id: "antalya", ar: "أنطاليا", en: "Antalya" },
    { id: "konya", ar: "قونية", en: "Konya" },
    { id: "adana", ar: "أضنة", en: "Adana" },
    { id: "gaziantep", ar: "غازي عنتاب", en: "Gaziantep" },
    { id: "sanliurfa", ar: "شانلي أورفة", en: "Sanliurfa" },
    { id: "kayseri", ar: "قيصري", en: "Kayseri" },
    { id: "mersin", ar: "مرسين", en: "Mersin" },
    { id: "diyarbakir", ar: "ديار بكر", en: "Diyarbakir" },
    { id: "hatay", ar: "هاتاي", en: "Hatay" },
    { id: "manisa", ar: "مانيسا", en: "Manisa" },
    { id: "kahramanmaras", ar: "قهرمان مرعش", en: "Kahramanmaras" },
    { id: "samsun", ar: "سامسون", en: "Samsun" },
    { id: "balikesir", ar: "بالق أسير", en: "Balikesir" },
    { id: "van", ar: "وان", en: "Van" },
    { id: "aydin", ar: "آيدن", en: "Aydin" },
    { id: "denizli", ar: "دنيزلي", en: "Denizli" },
    { id: "sakarya", ar: "صقاريا", en: "Sakarya" },
    { id: "trabzon", ar: "طرابزون", en: "Trabzon" },
    { id: "malatya", ar: "ملاطية", en: "Malatya" },
    { id: "erzurum", ar: "أرضروم", en: "Erzurum" },
    { id: "eskisehir", ar: "إسكي شهير", en: "Eskisehir" },
    { id: "kocaeli", ar: "قوجة إيلي", en: "Kocaeli" },
    { id: "mardin", ar: "ماردين", en: "Mardin" },
    { id: "tekirdag", ar: "تكيرداغ", en: "Tekirdag" },
    { id: "afyonkarahisar", ar: "أفيون", en: "Afyonkarahisar" },
    { id: "sivas", ar: "سيواس", en: "Sivas" },
  ],
  PK: [
    { id: "islamabad", ar: "إسلام آباد", en: "Islamabad" },
    { id: "punjab", ar: "البنجاب", en: "Punjab" },
    { id: "sindh", ar: "السند", en: "Sindh" },
    { id: "khyber-pakhtunkhwa", ar: "خيبر بختونخوا", en: "Khyber Pakhtunkhwa" },
    { id: "balochistan", ar: "بلوشستان", en: "Balochistan" },
    { id: "gilgit-baltistan", ar: "جلجت بلتستان", en: "Gilgit-Baltistan" },
    { id: "azad-kashmir", ar: "آزاد كشمير", en: "Azad Kashmir" },
    { id: "lahore", ar: "لاهور", en: "Lahore" },
    { id: "karachi", ar: "كراتشي", en: "Karachi" },
    { id: "peshawar", ar: "بيشاور", en: "Peshawar" },
    { id: "quetta", ar: "كويتا", en: "Quetta" },
    { id: "faisalabad", ar: "فيصل آباد", en: "Faisalabad" },
    { id: "multan", ar: "ملتان", en: "Multan" },
    { id: "rawalpindi", ar: "راولبندي", en: "Rawalpindi" },
  ],
  BD: [
    { id: "dhaka", ar: "دكا", en: "Dhaka" },
    { id: "chattogram", ar: "شيتاغونغ", en: "Chattogram" },
    { id: "khulna", ar: "خولنا", en: "Khulna" },
    { id: "rajshahi", ar: "راجشاهي", en: "Rajshahi" },
    { id: "sylhet", ar: "سيلهيت", en: "Sylhet" },
    { id: "barishal", ar: "بريشال", en: "Barishal" },
    { id: "rangpur", ar: "رنغبور", en: "Rangpur" },
    { id: "mymensingh", ar: "مايمنسينغ", en: "Mymensingh" },
  ],
  ID: [
    { id: "jakarta", ar: "جاكرتا", en: "Jakarta" },
    { id: "west-java", ar: "جاوة الغربية", en: "West Java" },
    { id: "central-java", ar: "جاوة الوسطى", en: "Central Java" },
    { id: "east-java", ar: "جاوة الشرقية", en: "East Java" },
    { id: "banten", ar: "بانتن", en: "Banten" },
    { id: "yogyakarta", ar: "يوجياكرتا", en: "Yogyakarta" },
    { id: "aceh", ar: "آتشيه", en: "Aceh" },
    { id: "north-sumatra", ar: "سومطرة الشمالية", en: "North Sumatra" },
    { id: "west-sumatra", ar: "سومطرة الغربية", en: "West Sumatra" },
    { id: "south-sumatra", ar: "سومطرة الجنوبية", en: "South Sumatra" },
    { id: "riau", ar: "رياو", en: "Riau" },
    { id: "jambi", ar: "جامبي", en: "Jambi" },
    { id: "bengkulu", ar: "بنجكولو", en: "Bengkulu" },
    { id: "lampung", ar: "لامبونغ", en: "Lampung" },
    { id: "riau-islands", ar: "جزر رياو", en: "Riau Islands" },
    { id: "bangka-belitung", ar: "بانكا بليتونغ", en: "Bangka Belitung" },
    { id: "west-kalimantan", ar: "كاليمانتان الغربية", en: "West Kalimantan" },
    { id: "central-kalimantan", ar: "كاليمانتان الوسطى", en: "Central Kalimantan" },
    { id: "south-kalimantan", ar: "كاليمانتان الجنوبية", en: "South Kalimantan" },
    { id: "east-kalimantan", ar: "كاليمانتان الشرقية", en: "East Kalimantan" },
    { id: "north-kalimantan", ar: "كاليمانتان الشمالية", en: "North Kalimantan" },
    { id: "north-sulawesi", ar: "سولاويسي الشمالية", en: "North Sulawesi" },
    { id: "central-sulawesi", ar: "سولاويسي الوسطى", en: "Central Sulawesi" },
    { id: "south-sulawesi", ar: "سولاويسي الجنوبية", en: "South Sulawesi" },
    { id: "southeast-sulawesi", ar: "سولاويسي الجنوبية الشرقية", en: "Southeast Sulawesi" },
    { id: "gorontalo", ar: "غورونتالو", en: "Gorontalo" },
    { id: "west-sulawesi", ar: "سولاويسي الغربية", en: "West Sulawesi" },
    { id: "bali", ar: "بالي", en: "Bali" },
    { id: "west-nusa-tenggara", ar: "نوسا تنقارا الغربية", en: "West Nusa Tenggara" },
    { id: "east-nusa-tenggara", ar: "نوسا تنقارا الشرقية", en: "East Nusa Tenggara" },
    { id: "maluku", ar: "مالوكو", en: "Maluku" },
    { id: "north-maluku", ar: "مالوكو الشمالية", en: "North Maluku" },
    { id: "papua", ar: "بابوا", en: "Papua" },
    { id: "west-papua", ar: "بابوا الغربية", en: "West Papua" },
  ],
  MY: [
    { id: "kuala-lumpur", ar: "كوالالمبور", en: "Kuala Lumpur" },
    { id: "selangor", ar: "سلانجور", en: "Selangor" },
    { id: "johor", ar: "جوهور", en: "Johor" },
    { id: "penang", ar: "بينانج", en: "Penang" },
    { id: "perak", ar: "بيراك", en: "Perak" },
    { id: "kedah", ar: "قدح", en: "Kedah" },
    { id: "kelantan", ar: "كلنتان", en: "Kelantan" },
    { id: "terengganu", ar: "ترينجانو", en: "Terengganu" },
    { id: "pahang", ar: "بهانج", en: "Pahang" },
    { id: "malacca", ar: "ملقا", en: "Malacca" },
    { id: "negeri-sembilan", ar: "نجري سمبيلن", en: "Negeri Sembilan" },
    { id: "perlis", ar: "بيرليس", en: "Perlis" },
    { id: "sabah", ar: "صباح", en: "Sabah" },
    { id: "sarawak", ar: "سراوق", en: "Sarawak" },
    { id: "labuan", ar: "لابوان", en: "Labuan" },
    { id: "putrajaya", ar: "بوتراجايا", en: "Putrajaya" },
  ],
  NG: [
    { id: "lagos", ar: "لاغوس", en: "Lagos" },
    { id: "abuja", ar: "أبوجا", en: "Abuja" },
    { id: "kano", ar: "كانو", en: "Kano" },
    { id: "kaduna", ar: "كادونا", en: "Kaduna" },
    { id: "rivers", ar: "ريفرز", en: "Rivers" },
    { id: "oyo", ar: "أويو", en: "Oyo" },
    { id: "sokoto", ar: "سوكوتو", en: "Sokoto" },
    { id: "borno", ar: "بورنو", en: "Borno" },
    { id: "katsina", ar: "كاتسينا", en: "Katsina" },
    { id: "delta", ar: "دلتا", en: "Delta" },
    { id: "edo", ar: "إيدو", en: "Edo" },
    { id: "anambra", ar: "أنامبرا", en: "Anambra" },
    { id: "enugu", ar: "إنوغو", en: "Enugu" },
    { id: "plateau", ar: "بلاتو", en: "Plateau" },
    { id: "niger", ar: "نيجر", en: "Niger" },
    { id: "bauchi", ar: "باوتشي", en: "Bauchi" },
    { id: "adamawa", ar: "أداماوا", en: "Adamawa" },
    { id: "kwara", ar: "كوارا", en: "Kwara" },
    { id: "ogun", ar: "أوغون", en: "Ogun" },
    { id: "osun", ar: "أوسون", en: "Osun" },
  ],
  IN: [
    { id: "delhi", ar: "دلهي", en: "Delhi" },
    { id: "maharashtra", ar: "مهاراشترا", en: "Maharashtra" },
    { id: "uttar-pradesh", ar: "أوتار براديش", en: "Uttar Pradesh" },
    { id: "west-bengal", ar: "غرب البنغال", en: "West Bengal" },
    { id: "kerala", ar: "كيرالا", en: "Kerala" },
    { id: "tamil-nadu", ar: "تاميل نادو", en: "Tamil Nadu" },
    { id: "karnataka", ar: "كارناتاكا", en: "Karnataka" },
    { id: "telangana", ar: "تيلانجانا", en: "Telangana" },
    { id: "gujarat", ar: "غوجارات", en: "Gujarat" },
    { id: "rajasthan", ar: "راجستان", en: "Rajasthan" },
    { id: "bihar", ar: "بيهار", en: "Bihar" },
    { id: "madhya-pradesh", ar: "مادهيا براديش", en: "Madhya Pradesh" },
    { id: "punjab", ar: "البنجاب", en: "Punjab" },
    { id: "haryana", ar: "هاريانا", en: "Haryana" },
    { id: "jammu-kashmir", ar: "جامو وكشمير", en: "Jammu & Kashmir" },
    { id: "assam", ar: "أسام", en: "Assam" },
    { id: "odisha", ar: "أوديشا", en: "Odisha" },
    { id: "jharkhand", ar: "جهارخاند", en: "Jharkhand" },
    { id: "andhra-pradesh", ar: "أندرا براديش", en: "Andhra Pradesh" },
  ],
};

export function citiesOf(country: string): City[] {
  return CITIES[country] ?? [];
}

export function cityName(city: City, lang: string): string {
  return lang === "ar" ? city.ar : city.en;
}

/** Key used to store a manual price for a country (and optionally one city). */
export function scopeKey(country: string, city?: string): string {
  return `${country}:${city && city.length > 0 ? city : "*"}`;
}
