/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FiqhRouteImport } from './routes/fiqh'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MapRouteImport } from './routes/map'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as TodayRouteImport } from './routes/today'
import { Route as TypesRouteImport } from './routes/types'
import { Route as WaqfRouteImport } from './routes/waqf'
import { Route as CountryCodeRouteImport } from './routes/country.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FiqhRoute = FiqhRouteImport.update({
  id: '/fiqh',
  path: '/fiqh',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const TypesRoute = TypesRouteImport.update({
  id: '/types',
  path: '/types',
  getParentRoute: () => rootRouteImport,
} as any)
const WaqfRoute = WaqfRouteImport.update({
  id: '/waqf',
  path: '/waqf',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeRoute = CountryCodeRouteImport.update({
  id: '/country/$code',
  path: '/country/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calculator': typeof CalculatorRoute
  '/compare': typeof CompareRoute
  '/countries': typeof CountriesRoute
  '/faq': typeof FaqRoute
  '/fiqh': typeof FiqhRoute
  '/history': typeof HistoryRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
  '/today': typeof TodayRoute
  '/types': typeof TypesRoute
  '/waqf': typeof WaqfRoute
  '/country/$code': typeof CountryCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calculator': typeof CalculatorRoute
  '/compare': typeof CompareRoute
  '/countries': typeof CountriesRoute
  '/faq': typeof FaqRoute
  '/fiqh': typeof FiqhRoute
  '/history': typeof HistoryRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
  '/today': typeof TodayRoute
  '/types': typeof TypesRoute
  '/waqf': typeof WaqfRoute
  '/country/$code': typeof CountryCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calculator': typeof CalculatorRoute
  '/compare': typeof CompareRoute
  '/countries': typeof CountriesRoute
  '/faq': typeof FaqRoute
  '/fiqh': typeof FiqhRoute
  '/history': typeof HistoryRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
  '/today': typeof TodayRoute
  '/types': typeof TypesRoute
  '/waqf': typeof WaqfRoute
  '/country/$code': typeof CountryCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calculator'
    | '/compare'
    | '/countries'
    | '/faq'
    | '/fiqh'
    | '/history'
    | '/map'
    | '/methodology'
    | '/today'
    | '/types'
    | '/waqf'
    | '/country/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/calculator'
    | '/compare'
    | '/countries'
    | '/faq'
    | '/fiqh'
    | '/history'
    | '/map'
    | '/methodology'
    | '/today'
    | '/types'
    | '/waqf'
    | '/country/$code'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calculator'
    | '/compare'
    | '/countries'
    | '/faq'
    | '/fiqh'
    | '/history'
    | '/map'
    | '/methodology'
    | '/today'
    | '/types'
    | '/waqf'
    | '/country/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CalculatorRoute: typeof CalculatorRoute
  CompareRoute: typeof CompareRoute
  CountriesRoute: typeof CountriesRoute
  FaqRoute: typeof FaqRoute
  FiqhRoute: typeof FiqhRoute
  HistoryRoute: typeof HistoryRoute
  MapRoute: typeof MapRoute
  MethodologyRoute: typeof MethodologyRoute
  TodayRoute: typeof TodayRoute
  TypesRoute: typeof TypesRoute
  WaqfRoute: typeof WaqfRoute
  CountryCodeRoute: typeof CountryCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiqh': {
      id: '/fiqh'
      path: '/fiqh'
      fullPath: '/fiqh'
      preLoaderRoute: typeof FiqhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/types': {
      id: '/types'
      path: '/types'
      fullPath: '/types'
      preLoaderRoute: typeof TypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waqf': {
      id: '/waqf'
      path: '/waqf'
      fullPath: '/waqf'
      preLoaderRoute: typeof WaqfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country/$code': {
      id: '/country/$code'
      path: '/country/$code'
      fullPath: '/country/$code'
      preLoaderRoute: typeof CountryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CalculatorRoute: CalculatorRoute,
  CompareRoute: CompareRoute,
  CountriesRoute: CountriesRoute,
  FaqRoute: FaqRoute,
  FiqhRoute: FiqhRoute,
  HistoryRoute: HistoryRoute,
  MapRoute: MapRoute,
  MethodologyRoute: MethodologyRoute,
  TodayRoute: TodayRoute,
  TypesRoute: TypesRoute,
  WaqfRoute: WaqfRoute,
  CountryCodeRoute: CountryCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
